name: Token Registration
description: Register metadata for Tapyrus colored coins
title: "[Token Registration] "
labels: ["token-registration"]
body:
  - type: markdown
    attributes:
      value: |
        ## Tapyrus Token Registry Registration Form
        Register token metadata compliant with TIP-0020 specification.

        This registry is for tokens that have already been issued. The metadata JSON should match exactly what was used to derive the Color ID.

  - type: dropdown
    id: network
    attributes:
      label: Network
      description: "Select the network where the token is issued (TIP-0044 compliant)"
      default: 1
      options:
        - "Tapyrus API - Network ID: 15215628"
        - "Tapyrus Testnet - Network ID: 1939510133"
    validations:
      required: true

  - type: input
    id: color_id
    attributes:
      label: Color ID
      description: "Token Color ID (c1/c2/c3 prefix + 64 hex characters)"
      placeholder: "c1a1b2c3d4e5f6..."
    validations:
      required: true

  - type: input
    id: payment_base
    attributes:
      label: Payment Base
      description: "Payment Base public key used to derive the P2C address (33 bytes compressed, hex)"
      placeholder: "02a1b2c3d4e5f6..."
    validations:
      required: true

  - type: input
    id: outpoint_txid
    attributes:
      label: OutPoint Txid (for Non-Reissuable/NFT only)
      description: "Transaction ID of the token issuance output (64 hex characters). Required for Non-Reissuable and NFT tokens."
      placeholder: "a1b2c3d4e5f6..."
    validations:
      required: false

  - type: input
    id: outpoint_index
    attributes:
      label: OutPoint Index (for Non-Reissuable/NFT only)
      description: "Output index of the token issuance output. Required for Non-Reissuable and NFT tokens."
      placeholder: "0"
    validations:
      required: false

  - type: textarea
    id: metadata
    attributes:
      label: Token Metadata (JSON)
      description: "TIP-0020 compliant token metadata in JSON format"
      placeholder: |
        {
          "name": "Example Token",
          "symbol": "EXT",
          "decimals": 8,
          "description": "An example token",
          "icon": "https://example.com/icon.png",
          "website": "https://example.com"
        }
      render: json
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I am the issuer of this token or have permission from the issuer to register
          required: true
        - label: The provided metadata matches what was used to derive the Color ID
          required: true
        - label: The information provided is accurate and does not contain false information
          required: true